### ISSUE TITLE
"/admin/api/cms" ActiveDocs not displayed in 3scale API Docs section

### ISSUE THREAD

**Issue by rmarins** [hguerrero/3scale-cms#2]
Using: **3scale-2.8.1.GA-onprem** on **OCP 4.4.12**

Where should I look for the Swagger or ActiveDocs for the CMS API ?

At path "/p/admin/api_docs#/account_management_api" of admin portal it's not displayed on any of following sections/operations categories:
- Service Management API
- Account Management API
- Analytics API
- Billing API
- Policy Registry API

Either cannot locate the API definition for "/admin/api/cms" at https://github.com/3scale/porta/tree/3scale-2.8.1-GA

**Comment by hguerrero** [comment]
The team finally documented the API here: https://github.com/3scale/porta/blob/3scale-2.8.1-GA/doc/active_docs/cms.json

Use that path for future reference.
